### ISSUE TITLE
clusterize list - nothing

### ISSUE THREAD

**Issue by dimd13** [A/node-clusterize-cli#6]
Установил, запустил 

```
clusterize --app ./app.js  --log ./cluster.log
```

, вызываю 

```
clusterize list
```

Говорит nothing, хотя приложение работает и процессы есть (два мастера и 8 воркеров)

**Comment by dimd13** [comment]
В коде есть команда

```
ps -eo pid,comm | grep "clusterize master"
```

ни чего не возвращает

```
ps -eo pid,comm | grep "clusterize"
```

возвращает все пиды процессов clusterize

**Comment by A** [comment]
Хм. А `ps aux | grep "clusterize master"` и `ps aux | grep clusterize` что говорят? Там более понятный вывод.

**Comment by A** [comment]
И ОС какая?

**Comment by dimd13** [comment]
ОСь Debian 7.1 
эта команда отрабатывает нормально

```
ps aux | grep "clusterize master"

root      8956  0.0  1.0 593016 10572 ?        Ssl  22:21   0:00 clusterize master /var/www/test/app.js                                          
root      9052  0.0  0.0   7852   844 pts/3    S+   22:40   0:00 grep clusterize master
```

**Comment by dimd13** [comment]
Интересно

```
ps -eo pid,comm | grep "clusterize mast"
```

pid находит

```
ps -eo pid,comm | grep "clusterize maste"
```

нет pid'а

**Comment by A** [comment]
Ясно. Попробую поправить. Пока можно просто убивать процесс `clusterize master` по pid с помощью `kill -9 8956`, он сам должен завершить всех детей. Вообще, `list` и `kill` как раз и задумывались как алиасы для этих комманд для удобства, но похоже надо еще поработать над кросс-платформенностью.

**Comment by A** [comment]
Вообще, мне кажется, что самым простым решением будет заменить `ps -eo pid,comm | grep "clusterize master"` на `ps -eo pid,comm | grep "clusterize mast"` но меня смущает то, что я не понимаю, почему одно работает, а другое — нет. @dimd13 может быть у вас есть какие-то идеи на этот счет?

**Comment by dimd13** [comment]
Думаю имя процесса режет из-за этого (из офф доки nodejs process.title):

```
On Linux and OS X, it's limited to the size of the binary name plus the length of the command line arguments because it overwrites the argv memory
```

**Comment by dimd13** [comment]
Изменил имя процесса на более короткое master_pid `ps -eo pid,comm | grep "master_pid"` отрабатывает нормально, только имени приложения не видно, выдает только

```
3520 master_pid /var/
```

и как следствие `clusterize list` ошибки на регулярки валятся...

Не влезает в process.title имя процесса и полный путь приложения! Надо думать, что с этим делать.

**Comment by A** [comment]
Может быть назвать `clstr mstr %app` и `clstr wkr`?

**Comment by dimd13** [comment]
Сделал так в bin/clusterize изменил `ps -eo pid,comm | grep "clusterize master` на `ps -axo pid,args | grep "clusterize master" | grep -v grep` и вывод поправил:

```
/**
 * Print list of running daemons
 */
if (program.list) {
  return exec('ps -axo pid,args | grep "clusterize master" | grep -v grep', function (err, stdout) {
    if (!stdout) return console.log('nothing'.red);
    console.log(stdout.green)
  });
}

```

выводит без регулярок pid и путь к приложению:

```
root@debby: /var/www/test# clusterize list
 5115 clusterize master /var/www/test/app.js                                                      
 5521 clusterize master /var/www/test/test.js
```

Все работает!!!

**Comment by A** [comment]
Как насчет PR? Буду очень признателен!

**Comment by dimd13** [comment]
Не понял, что есть PR, я не давно на гите может чего не знаю?

**Comment by A** [comment]
pull request. https://help.github.com/articles/using-pull-requests

**Comment by dimd13** [comment]
Сделал.

**Comment by A** [comment]
Смержил. Сейчас можно установить через `npm i -g shuvalov-anton/node-clusterize-cli`. Я у себя на Mac OS сейас проверю, и выложу в npm к вечеру.

**Comment by A** [comment]
На OS X. Странный вывод.

```
➜  node-blog git:(master) ✗ clusterize -a ./app.js                     
done
➜  node-blog git:(master) ✗ clusterize list       
26342 clusterize master /Users/antonshuvalov/Desktop/node-blog/ TERM_PROGRAM=Apple_Terminal SHELL=/bin/zsh TERM=xterm
```

**Comment by A** [comment]
@dimd13 `args` тянет за собой еще и аргументы вызова. Попробуй сейчас, работает?

**Comment by dimd13** [comment]
А эта команда как отрабатывает:

```
ps aux | grep "clusterize master" | grep -v grep | awk  '{print $2 " " $11 " "  $12 " " $13}'
```

**Comment by A** [comment]
Хорошо отрабатывает. Как надо

**Comment by A** [comment]
Может быть так:

```
ps aux | grep "clusterize master" | grep -v grep | awk  \'{print $2 \" \" $13}\'
```

Мне кажется что название процесса `clusterize master` не несет пользы.

**Comment by dimd13** [comment]
Можно сделать так:
lib/node-clusterize.js

```
cluster.isMaster
    ? process.title = options.app + ' clusterize master'
    : process.title = options.app + ' clusterize worker ';
```

, а поиск сменить на:

```
ps aux | grep "clusterize master" | grep -v grep | awk  \'{print $2 \" \" $11}\'
```

т.к. $2 - это pid, а с $11 и далее это комментарий \ название процесса, программа ищет по части названия мастер процесса (который могут захотеть изменить) и выводить, что да это мастер не обязательно, главное видеть, что это за приложение и его pid чтоб знать что грохать.

вывод станет:

```
root@debby: /var/www/test# clusterize list
22115 /var/www/test/app.js
```

**Comment by A** [comment]
Думаю, да. Давай так и сделаем!

**Comment by dimd13** [comment]
Сделал Pull

**Comment by A** [comment]
Там была конфликт. Сейчас все поправил. Проверяй

**Comment by dimd13** [comment]
Все работает! Закрываю!
